### ISSUE TITLE
key mapping not work

### ISSUE THREAD

**Issue by rmGFW** [voldikss/coc-translator#103]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/66858140/100037610-71ad5600-2e3d-11eb-8e8b-754fb7082f1a.png">
添加key mapping 以后 ，按下以后没有翻译，而是在第一行输入了一些错误的字

**Comment by voldikss** [comment]
快捷键添加得不对，像所有的这种 `<Plug>(...)` 之类的 mappings, 以后都不要用 `nore`，因为这样的话就组织了传递（`<Plug>`本身也是一个被映射的快捷键）

所以只用 `nmap` 就行了
