### ISSUE TITLE
After setting translator.engines , it does not work

### ISSUE THREAD

**Issue by wanghongfucoder** [voldikss/coc-translator#111]
由于国内google访问不了，所以设置翻译引擎，在coc-settings.json中设置了 "translator.engines" = ["bing","youdao","haici"], 如下图所示，
![image](https://user-images.githubusercontent.com/12027007/135416895-fef63a67-fd15-44d5-b901-aa84031dafaa.png)
但是仍报错google无法访问的错误
![image](https://user-images.githubusercontent.com/12027007/135417172-f30770e4-c03d-4598-9d25-70315113c0a7.png)

**Comment by voldikss** [comment]
fixed.
