### ISSUE TITLE
Help：根据不同使用场景选择不同的搜索引擎

### ISSUE THREAD

**Issue by Delayless** [voldikss/coc-translator#113]
大佬，有没有什么方法可以自定义调用的搜索引擎
就是我发现google翻译句子挺棒，但是翻译单词托慢了运行速度。
我想nmap就用bing/youdao，vmap就用google

**Comment by voldikss** [comment]
暂时还不行哦，做得比较简陋，这个功能还不支持

**Comment by voldikss** [comment]
可以看下这个

https://github.com/voldikss/vim-translator#translate

**Comment by Delayless** [comment]
> 可以看下这个
> 
> https://github.com/voldikss/vim-translator#translate

这个也在用，但是感觉coc-translator运行快一些

**Comment by voldikss** [comment]
> 这个也在用，但是感觉coc-translator运行快一些

是的，我最近也发现速度慢了好多，好像是调的翻译的接口变慢了，一直没空修。

桌面端的话，推荐下 goldendict 挺好用的，我在用。知乎上可以搜到 skywind3000 的教程，超级好用。

**Comment by Delayless** [comment]
> 

这个我也在用[笑哭]
Ctrl+c c翻译确实很舒服
就是经常在vim，用vim插件更方便。

那就这样吧，issue先关了？感谢大佬开发的插件

**Comment by voldikss** [comment]
:ok_hand:
