### ISSUE TITLE
socks proxy not working

### ISSUE THREAD

**Issue by AvavaAvaOrange** [voldikss/coc-translator#119]
我用的clash 使用privoxy来让http/https 走socks代理

环境变量代理配置
~~~shell
export HTTP_PROXY="http://127.0.0.1:8118"
export HTTPS_PROXY=$HTTP_PROXY
~~~
privoxy配置
~~~shell
forward-socks5t / 127.0.0.1:7890 .
~~~

Coc配置
~~~shell
    "translator.proxy": "socks5://127.0.0.1:7890",
    "translator.engines": [
        "google",
        "youdao"
    ],
~~~

执行coc-translation翻译，只有Google和bing的翻译引擎不工作(不怎么用bing，但试过了他也没工作)，代理确定没有问题，其它程序都能用socks代理，请问我这是哪里没配置好？

**Comment by voldikss** [comment]
@AvavaAvaOrange 解决了吗？抱歉在忙没顾上回复

**Comment by AvavaAvaOrange** [comment]
> @AvavaAvaOrange 解决了吗？抱歉在忙没顾上回复

没事，已经解决了，iptables没配置好。

麻烦了，谢谢
