### ISSUE TITLE
coc#util#echo_message is abandoned

### ISSUE THREAD

**Issue by pacmanzou** [voldikss/coc-translator#121]
![](https://fastly.jsdelivr.net/gh/pacmanzou/pictures@main/16559245684011655924567635.png)

(coc-translator-e)， it does't work now.

**Comment by pacmanzou** [comment]
I know it, now the name of the function is coc#ui#echo_messages

**Comment by nemobb** [comment]
There is no content for this merge commit (https://github.com/voldikss/coc-extensions/commit/460e5a1ae75b8aa01336e3badf69baab099b571a) on the main branch， can you resolve it？

**Comment by pacmanzou** [comment]
> There is no content for this merge commit ([460e5a1](https://github.com/voldikss/coc-extensions/commit/460e5a1ae75b8aa01336e3badf69baab099b571a)) on the main branch， can you resolve it？

All right now.
