### ISSUE TITLE
[feature request]: 大佬，请求添加离线词典文件的支持

### ISSUE THREAD

**Issue by cossonleo** [voldikss/coc-translator#17]
大佬，请求添加离线词典文件的支持
例如: mdx, eudic词典文件的支持

**Comment by voldikss** [comment]
感谢建议，有空了我试着加下。

**Comment by voldikss** [comment]
Hi @cossonleo @lightxue 

发现有人做了一个使用使用本地词库的扩展， 速度很快，你们急需的话可以试试。https://github.com/fannheyward/coc-ecdict

**Comment by ChenWeird** [comment]
期待

**Comment by voldikss** [comment]
暂时没时间加了，已经有扩展用可以用本地词典了。你可以试试 coc-ecdict @VimVim

VimVim <notifications@github.com> 于 2020年1月19日周日 上午5:15写道：

**Comment by voldikss** [comment]
已经有了 coc-ecdict，我觉得这个就没有必要加了。所以我就先关闭这个 issue 了。
