### ISSUE TITLE
Moonshot: rikaichan

### ISSUE THREAD

**Issue by teto** [voldikss/coc-translator#23]
Seeing your plugin reminded me of this extension https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/ which I am fond of, basically when you hover over a japanese/chinese word, a popup opens with the meanings/pronunciation of the kanji and the differents words that can be created from the neighboring kanjis.

I would love to have this kind of behavior in vim, i.e., having a popup that translates the kanji (and the compositions with its surrounding) next to the cursor.

It might be out of scope for you but I thought I would mention it anyway. Feel free to close if that's the case.

**Comment by voldikss** [comment]
It's a pretty good idea which I have seen and experienced it VSCode. Sadly I will be busy with other stuff near future. So it would be best to leave this issue open and I will have a try someday

**Comment by voldikss** [comment]
BTW, @teto  I wonder the issue you mentioned in #9 still exist or has gone away

**Comment by teto** [comment]
thanks for being open minded, I answered on the other issue (spoiler: the issue still exists)

**Comment by voldikss** [comment]
I've add an option `translator.enableHover` for that.
