### ISSUE TITLE
Get error with coc-translator-p

### ISSUE THREAD

**Issue by cycoe** [voldikss/coc-translator#32]
老哥，感谢你做的插件，我遇到一个 bug
但我使用 popup 模式的时候 "nmap <Leader>k <Plug>(coc-translator-p)", 
就会出现 "[coc.nvim] error: error on notification 'doKeymap': TypeError: Cannot read property 'uri' of undefined"
echo 模式没有问题

我的 coc 设置为
    "translator.toLang": "zh",
    "translator.engines": ["bing", "google"]

**Comment by voldikss** [comment]
欸我这里正常的，要不把你翻译的那个文本告诉我下

**Comment by voldikss** [comment]
还是不管翻译什么都报错？

**Comment by cycoe** [comment]
不管翻译什么都报错，刚刚尝试 'voldikss/vim-translate-me' 也无法使用 popup，是不是我的 neovim 不支持 floating window

**Comment by voldikss** [comment]
nvim 的版本是 0.4.0 吗，

**Comment by cycoe** [comment]
是 0.3.8
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by voldikss** [comment]
哦那就是因为没有 floating 支持了。

**Comment by voldikss** [comment]
建议用 0.4.0，很稳健，我没遇到过 bug

**Comment by cycoe** [comment]
好的多谢老哥:)

**Comment by voldikss** [comment]
不客气:)
