### ISSUE TITLE
Set the floating window highlight to 'CocFloating'?

### ISSUE THREAD

**Issue by linjiX** [voldikss/coc-translator#59]
About the default highlight for floating window:
- `NormalFloat` for Neovim
- `Pmenu` for Vim8 (Popup window)

Which makes the color of floating window different in Neovim and vim8.

So I think it will be better to make the highlight configurable by user.
Or set the default highlight to `CocFloating` since this is a coc plugin.

**Comment by voldikss** [comment]
Thanks. fixed.
