### ISSUE TITLE
error on notification 'doKeymap': 

### ISSUE THREAD

**Issue by teto** [voldikss/coc-translator#9]
I tried to call coc-translator via the mapping `nmap <Leader>te <Plug>(coc-translator-p)` on some japanese text but it gives me:

```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.16.0
coc.nvim version: 0.0.72-22daa03a7d
term: xterm-termite
platform: linux

## Messages
"content/dechets.md" 28L, 1022C
[coc.nvim] error: error on notification 'doKeymap': TypeError: Cannot read property 'index' of null
## Output channel: snippets

```

My coc config is : 
```
	"translator.toLang": "fr",
	// "bing", "ciba",
	"translator.engines": [ "google"],
	// history size
	"translator.maxsize": 5000, 
```

**Comment by teto** [comment]
how does the engine work ? I've tried to call the mapping on a visual range but it returns `No range allowed`. Would be nice to support it :)

**Comment by voldikss** [comment]
Thank you for testing this plugin! I have run into this problem before. But I tested it just now and found it was gone. Could you upgrade coc/coc-translator to the lastest version and test again?

**Comment by voldikss** [comment]
As a coc's extension, its keymap was defined here
https://github.com/voldikss/coc-translator/blob/master/src/index.ts#L19-L33

The engine classes was wrote in the [translator.ts](https://github.com/voldikss/coc-translator/blob/master/src/translator.ts) file. But currently I can't figure out how to define a visual keymap and make it workable. So I added it into the [TODO](#8)

**Comment by teto** [comment]
I was already using the latest coc-translator. I've bumped coc-nvim runtime (still using 0.72 for th binary though) but still gets the error :s

**Comment by voldikss** [comment]
Hmmm, sorry I still can not reproduce this issue. It's weird somehow

**Comment by teto** [comment]
no pb this kind of issue tends to go away with time, after several package updates; I will wait :)

btw I work with several different languages so I would like to specify the target/origin language when mapping. I feel like it's impossible right now ?

**Comment by voldikss** [comment]
> btw I work with several different languages so I would like to specify the target/origin language when mapping.

Hi @teto If you want to create various keymaps according to the languages, you can use https://github.com/voldikss/vim-translate-me, which is developed using VimL. I just refine its command and make it easy to pass `target language` argument.

e.g. 
```vim
nmap <silent>    <Leader>tf   :TranslateW -e bing google -l fr<CR>
nmap <silent>    <Leader>tj   :TranslateW -e bing google -l ja<CR>
```

**Comment by teto** [comment]
haha I used to use that one but I liked the idea of displaying the translation in floating windows, hence I switched to this one (as I already used the excellent coc)

**Comment by voldikss** [comment]
That plugin also display the translation in floating windows(for nvim) or popup(for vim81). Moreover, viml is easier to handle some stuff such as keymap.

Yes, coc is super sexy.

**Comment by perfectspr** [comment]
got the save issue when 
`nmap <Leader>t <Plug>(coc-translator-p)`
got below issue when 
`nmap <Leader>e <Plug>(coc-translator-e) `

`[coc.nvim] error: error on notification 'doKeymap': TypeError: Cannot read property 'query' of undefined `

**Comment by voldikss** [comment]
@perfectspr 
Could you give me the text under the cursor(so that I can reproduce that issue)?

**Comment by teto** [comment]
still present (just ran on `店`)
CocInfo
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.16.0
coc.nvim version: 0.0.73-56825890dc
term: xterm-termite
platform: linux

## Messages
"content/nixos_testing_infra.md" 55L, 1613C
"content/restauration.md" 38L, 1166C
1 modification ; avant #1 ; il y a 1 seconde
"content/restauration.md" 38 lines --28%--
[coc.nvim] error: error on notification 'doKeymap': TypeError: Cannot read property 'index' of null
## Output channel: snippets
```

**Comment by voldikss** [comment]
@teto I just located the bug and fixed it.

**Comment by teto** [comment]
thanks ! it works.
One strange thing is that google seems to return a character that can't be displayed ?
This is the content of the floating window when trying to translate the  kanji 店
```
           @ 店内 @
 
--------- google ---------
🌀 À l'intérieur du magasin
```
the block/square on the last line is:
`'🌀' U+1F300 Dec:127744 CYCLONE &#x1F300; /\%U1f300 "\U1f300"`. Shouldn't it display the same kanji ? or is that a network error ?

**Comment by voldikss** [comment]
Maybe that's because google engine cannot translate it correctly I think... I will check it for you

**Comment by teto** [comment]
so github displays correctly the `cyclon` codepoint (but in my terminal, it was the glyph for unknown glyph). Anyway strange to use a cyclon instead of  店内.

**Comment by voldikss** [comment]
Sorry I didn't figure out what's the real problem. Do you mean `cyclon` isn't displayed correctly or the translation text `À l'intérieur du magasin` is invalid? Could you take a screenshot for that?

**Comment by teto** [comment]
The translation is correct, I just find it weird that my term is asked to display 'cyclon' instead of the kanji it was asked to translate:
![coc-translator](https://user-images.githubusercontent.com/886074/62435302-96784880-b776-11e9-90bc-b027e84860e4.jpg)

**Comment by voldikss** [comment]
Hmmm I am not aware that emoji may not be displayed correctly in some terminal. :neckbeard:
