### ISSUE TITLE
Translator popup will produce lots of useless "[Scratch]" buffers

### ISSUE THREAD

**Issue by linjiX** [voldikss/coc-translator#90]
Every time the translator popup window appears, it will create a "[Scratch]" buffer.
After the popup window is closed, the "[Scratch]" buffer will not be removed.
Also the next time the translator popup window appears, the previous "[Scratch]" buffer will not be reused. Instead it will create a new one.
After using coc-translator multiple times, there will be full of useless "[Scratch]" buffers in the buffer list.

- neovim v0.4.3
- MacOS

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim, also coc-translator could just use FloatFactory module replace it's window module.
