### ISSUE TITLE
[coc.nvim]: Error on notification "doKeymap": this.engines is not iterable

### ISSUE THREAD

**Issue by ztoiax** [voldikss/coc-translator#96]

**Comment by voldikss** [comment]
Hi, could you also provider your corresponding configuration in coc-settings.json?

**Comment by ztoiax** [comment]
https://github.com/ztoiax/nvim/blob/master/coc-settings.json
用中文交流吧

最上川 <notifications@github.com> 于2020年8月16日周日 上午8:25写道：

**Comment by voldikss** [comment]
https://github.com/ztoiax/nvim/blob/master/coc-settings.json#L165-L197

将这些配置部分移除就可以了

**Comment by voldikss** [comment]
https://github.com/voldikss/coc-translator#configuration

这里给出的只是每项配置的具体格式说明，你要自定义的话不能按照这个写。
比如对于
```jsonc
"translator.engines": {
  "type": "array",
  "default": [
    "google",
    "youdao",
    "haici"
  ]
},
```
正确的写法是（举例）
```jsonc
"translator.engines":  [
    "google",
    "youdao",
    "haici"
  ]
```

**Comment by ztoiax** [comment]
谢谢

最上川 <notifications@github.com> 于2020年8月17日周一 下午5:38写道：
