### ISSUE TITLE
Bing接口有点问题

### ISSUE THREAD

**Issue by Delayless** [voldikss/coc-translator#98]
如题，Bing接口好像只能翻译单词不能翻译句子，所以翻译句子不会返回结果而且会报错 Translating Error： Bad Response，你加这层校验的目的如果是想验证接口有没有失效的话可能这种方法不是最好的，因为实际上翻译单词Bing这个接口是没问题的，我现在自己的处理方式是：
```javascript
    let BingTransAPI = 'http://cn.bing.com/dict/SerpHoverTrans'
    let url = BingTransAPI
    url += '?q=' + encodeURIComponent(text)

    const resCheckAPI = await request('GET', BingTransAPI, 'text', null, headers)
    if (!resCheckAPI) {
        showMessage(`${this.name} Translating Error: Bad Response`, 'error')
        return result
    }

    const res = await request('GET', url, 'text', null, headers)
    if (!res) {
      return result
    }
```
很丑陋所以没有提PR，每次翻译都要多一次请求（主页是有结果返回的，所以用来校验），我也不会这个语言，能优化一下这一块吗？

**Comment by voldikss** [comment]
嗯，所以应该将 `showMessage(`${this.name} Translating Error: Bad Response`, 'error')` 直接去掉，不成功时不报错就可以了。你觉得可以吗

**Comment by voldikss** [comment]
我也不是 ts 精通者，不过写这些东西和流水账一样用不到高级技巧 :joy:

**Comment by Delayless** [comment]
> 嗯，所以应该将 `showMessage(`${this.name} Translating Error: Bad Response`, 'error')` 直接去掉，不成功时不报错就可以了。你觉得可以吗

刚开始我也是直接注视掉，不过后来想了想，校验也是有合理性的，可以提醒更新接口嘛，最好是加个标志位，把那个if(res)改成标志位，第一次运行时候校验一次，之后就不用了，至于校验方法我写的就可以用，不加任何参数就是首页是有数据的。可以用来校验。

**Comment by Delayless** [comment]
另外deepL翻译效果很好，我都分析了一下接口数据写到我的TODO了，不过我不会这个语言，只能照葫芦画瓢，得搁置一段时间，如果你有时间愿意写的话那就最好了。也是json格式的request请求

**Comment by voldikss** [comment]
提醒更新接口这个想法很棒。其实只要在你写的代码中将两次请求调换过来就好了，即先执行查询，如果成功，则不用再校验；反之则可以进行一次校验。这样会好一些。

不过我想直接注释掉，一则是因为我觉得bing这个接口应该会长期存在，二则是因为我比较懒。其实 Google 翻译引擎也可以用的，而且效果不错，这几个当中我就觉得bing最不好用了，你或者也可以尝试下其他的几个。

**Comment by voldikss** [comment]
> 另外deepL翻译效果很好，我都分析了一下接口数据写到我的TODO了，不过我不会这个语言，只能照葫芦画瓢，得搁置一段时间，如果你有时间愿意写的话那就最好了。也是json格式的request请求

OK，我先弄了个 issue 记下来，#99

**Comment by voldikss** [comment]
closed by 1477863
